# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('reserve', models.TextField(blank=True, verbose_name='Резерв')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('reserve', models.TextField(blank=True, verbose_name='Резерв')),
            ],
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
                ('pub', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.PositiveIntegerField(max_length=100, unique=True, verbose_name='Код')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('text_1', models.TextField(verbose_name='Описание 1')),
                ('text_2', models.TextField(blank=True, verbose_name='Описание 2')),
                ('text_3', models.TextField(blank=True, verbose_name='Описание 3')),
                ('character_1', models.CharField(blank=True, max_length=50, verbose_name='Характеристика 1')),
                ('character_2', models.CharField(blank=True, max_length=50, verbose_name='Характеристика 2')),
                ('character_3', models.CharField(blank=True, max_length=50, verbose_name='Характеристика 3')),
                ('character_4', models.CharField(blank=True, max_length=50, verbose_name='Характеристика 4')),
                ('character_5', models.CharField(blank=True, max_length=50, verbose_name='Характеристика 5')),
                ('character_6', models.CharField(blank=True, max_length=50, verbose_name='Характеристика 6')),
                ('character_7', models.CharField(blank=True, max_length=50, verbose_name='Характеристика 7')),
                ('pub', models.DateTimeField(verbose_name='date published')),
                ('price', models.FloatField(verbose_name='Цена, грн.')),
                ('sale', models.PositiveSmallIntegerField(default=0, verbose_name='Скидка, %')),
                ('image_1', models.CharField(blank=True, max_length=75, verbose_name='Изображение 1')),
                ('image_2', models.CharField(blank=True, max_length=75, verbose_name='Изображение 2')),
                ('image_3', models.CharField(blank=True, max_length=75, verbose_name='Изображение 3')),
                ('image_4', models.CharField(blank=True, max_length=75, verbose_name='Изображение 4')),
                ('image_5', models.CharField(blank=True, max_length=75, verbose_name='Изображение 5')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Есть в наличии')),
                ('like', models.IntegerField(default=0, verbose_name='Нравится')),
                ('reserve_1', models.TextField(blank=True, verbose_name='Резерв 1')),
                ('reserve_2', models.CharField(blank=True, max_length=50, verbose_name='Резерв 2')),
                ('reserve_3', models.FloatField(blank=True, verbose_name='Резерв 3')),
                ('accessory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Accessory', verbose_name='Подкатегория')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Категория')),
            ],
            options={
                'ordering': ['-pub', 'name'],
            },
        ),
        migrations.AddField(
            model_name='coment',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Good'),
        ),
    ]
