# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20171028_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='good',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='good',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='good',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='good',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='good',
            name='text_1',
        ),
        migrations.RemoveField(
            model_name='good',
            name='text_2',
        ),
        migrations.RemoveField(
            model_name='good',
            name='text_3',
        ),
        migrations.AddField(
            model_name='good',
            name='image',
            field=models.CharField(blank=True, max_length=500, verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='good',
            name='link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Связь'),
        ),
        migrations.AddField(
            model_name='good',
            name='text',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='good',
            name='accessory',
            field=models.CharField(blank=True, max_length=50, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='good',
            name='like',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во оценок'),
        ),
        migrations.AlterField(
            model_name='good',
            name='reserve_2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Резерв 2'),
        ),
        migrations.DeleteModel(
            name='Accessory',
        ),
    ]
