# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171029_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='like',
            new_name='number',
        ),
        migrations.AddField(
            model_name='good',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='text',
            field=models.TextField(),
        ),
    ]
