# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Формируется'), (2, 'Оформлен'), (3, 'Обрабатывается'), (4, 'Отправлен'), (5, 'Оплачен'), (6, 'Получен'), (7, 'Возвращён'), (8, 'Отменён'), (9, 'Резерв')], verbose_name='Статус заказа'),
        ),
    ]
